---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8 tests
  ansible-lint -x 208,106 .
platforms:
  - name: 20220522.0.57327
    image: archlinux:base-20220522.0.57327
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
  - name: latest
    image: archlinux:latest
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
scenario:
  name: archlinux
verifier:
  name: testinfra
  directory: ../../tests/default
  options:
    verbose: true
