---
# tasks to install GLIBC on Alpine Linux

- name: Check for GLIBC packages in Alpine Linux
  command: apk info --installed {{ item }}
  changed_when: false
  ignore_errors: true
  with_items: '{{ alpine_glibc_pkg_names }}'
  register: alpine_glibc_test

- name: Set Alpine GLIBC packages to install
  set_fact:
    alpine_glibc_pkgs_to_install: >-
      {{ alpine_glibc_test.results |
         selectattr("rc", "equalto", 1) |
         map(attribute="item") |
         list }}

- name: Download GLIBC files pkgs for Alpine Linux
  get_url:
    url: >-
      {{ alpine_glibc_download_url }}/{{ item }}-{{ alpine_glibc_version }}.apk
    dest: '{{ sdkman_tmp_dir }}/'
  with_items: '{{ alpine_glibc_pkgs_to_install }}'

- name: Add sgerrand's public key
  get_url:
    url: '{{ alpine_glibc_pubkey_url }}'
    dest: /etc/apk/keys/

- name: Install GLIBC for Alpine Linux
  apk:
    name: '{{ sdkman_tmp_dir }}/{{ item }}-{{ alpine_glibc_version }}.apk'
    state: present
  with_items: '{{ alpine_glibc_pkgs_to_install }}'
  become: yes

- name: Cleanup GLIBC apk files
  file:
    path: '{{ sdkman_tmp_dir }}/{{ item }}-{{ alpine_glibc_version }}.apk'
    state: absent
  with_items: '{{ alpine_glibc_pkgs_to_install }}'
