---
# tasks file for ansible-sdkman

- name: Install SDKMAN
  include_tasks: install.yml

- block:
    - name: Run SDKMAN tasks
      include_tasks: sdkman.yml
  environment:
    SDKMAN_DIR: '{{ sdkman_dir }}'
  become: '{{ sdkman_user != ansible_user_id }}'
  become_user: '{{ sdkman_user }}'
