# Molecule managed

FROM {{ item.image }}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get upgrade -y && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ]; then  if [[ $(cat /etc/os-release | grep PLATFORM_ID) == *'el8'* ]]; then dnf --assumeyes install python36 sudo python36-devel python3-dnf bash && update-alternatives --set python /usr/bin/python3 ; else dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash;  fi; dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper update -y && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates shadow; fi

RUN groupadd jenkins
RUN useradd -g jenkins -d /home/jenkins -m -s /bin/bash jenkins
RUN echo 'jenkins ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers
