---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8 tests
  ansible-lint -x 208,106 .
platforms:
  - name: buster
    image: debian:buster
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
  - name: stretch
    image: debian:stretch
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
scenario:
  name: debian
verifier:
  name: testinfra
  directory: ../../tests/default
  options:
    verbose: true
