---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8 tests
  ansible-lint -x 208,106 .
platforms:
  - name: alpine-edge
    image: alpine:edge
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
  - name: alpine-3-13
    image: alpine:3.13
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
  - name: alpine-3-12
    image: alpine:3.12
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
  - name: alpine-3-11
    image: alpine:3.11
    user: ${MOLECULE_USER}
    dockerfile: ../default/Dockerfile.j2
    tty: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ./converge.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
scenario:
  name: alpine
verifier:
  name: testinfra
  directory: ../../tests/alpine
  options:
    verbose: true
    debug: true
